import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middlewares/error.middleware.js';
import authRoutes from './routes/auth.routes.js';
import transactionRoutes from './routes/transaction.routes.js';
import budgetRoutes from './routes/budget.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import aiRoutes from './routes/ai.routes.js'; import billRoutes from './routes/bill.routes.js';
import { walletRoutes, goalRoutes, loanRoutes } from './routes/resources.routes.js'; import notificationRoutes from './routes/notification.routes.js'; import analyticsRoutes from './routes/analytics.routes.js';
import adminRoutes from './routes/admin.routes.js';

const app = express();
if (env.nodeEnv === 'production') app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.clientUrl, credentials: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300, standardHeaders: 'draft-7', legacyHeaders: false }));
app.use(express.json({ limit: '1mb' })); app.use(express.urlencoded({ extended: true })); app.use(cookieParser());
app.use('/uploads', express.static('uploads'));
if (env.nodeEnv !== 'test') app.use(morgan('dev'));
app.get('/api/v1/health', (req, res) => res.json({ success: true, data: { status: 'ok', timestamp: new Date().toISOString() } }));
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/transactions', transactionRoutes); app.use('/api/v1/budgets', budgetRoutes); app.use('/api/v1/dashboard', dashboardRoutes);
app.use('/api/v1/ai', aiRoutes); app.use('/api/v1/bills', billRoutes);
app.use('/api/v1/wallets', walletRoutes); app.use('/api/v1/goals', goalRoutes); app.use('/api/v1/loans', loanRoutes); app.use('/api/v1/notifications', notificationRoutes); app.use('/api/v1/analytics', analyticsRoutes);
app.use('/api/v1/admin', adminRoutes);
app.use(notFound); app.use(errorHandler);
export default app;
